### ISSUE TITLE
Link property

### ISSUE THREAD

**Issue by danfri86** [wp-papi/papi#99] opened 2015-10-08 08:39 UTC
When using the link property and saving a post, the saved data is not displayed.
Also, when getting the object in frontend it contains only title and target. Missing the url and title.

**Comment by frozzare** [comment] 2015-10-08 08:43
Which Papi version? It's not good leave out information like version and so. 






On torsdag 8 okt. 2015 at 10:39, danfri86 <notifications@github.com>, wrote:

When using the link property and saving a post, the saved data is not displayed.

Also, when getting the object in frontend it contains only title and target. Missing the url and title.

**Comment by danfri86** [comment] 2015-10-08 08:45
Sorry, version 2.4.0-dev.

**Comment by frozzare** [comment] 2015-10-08 08:54
Well, 2.4.0-dev is unstable and should not be used if you don't know what you're doing. I will look at this when I have time.






On torsdag 8 okt. 2015 at 10:45, danfri86 <notifications@github.com>, wrote:
Meddelandets innehåll kan inte visas just nu

**Comment by danfri86** [comment] 2015-10-08 08:57
I was running version 2.3.4 when first noticed and upgraded shortly after.
Sounds good, thank you.

**Comment by frozzare** [comment] 2015-10-08 14:40
I can't reproduce this. Can you describe how to reproduce this?

**Comment by danfri86** [comment] 2015-10-12 07:26
I add my property page type and property with this:

    class Teaser_Page_Type extends Papi_Page_Type {
        public function page_type() {
            return [
                'name'          => 'Standard',
                'description'   => '',
                'post_type'     => 'teaser',
                'template'      => get_template_directory_uri() .'/page-templates/teaser.php',
                'standard_type' => false, // If standard box is shows or not
            ];
        }

        public function register() {
            $this->box( 'Länk', [
                papi_property([
                    'title'    => 'Länk',
                    'type'     => 'link',
                    'slug'     => 'url',
                    'sidebar'  => false
                ])
            ]);
        }
    }

When creating a new post I'm linking to an existing page, adding linktext and check the box to open in a new window. All data gets saved in the database but not displayed in the admin-ui.

Getting the data in my template with this:

    $url_obj = papi_get_field('url');

and output with:

    print_r($url_obj);

gives med:

    stdClass Object ( [title] => Knapptext [target] => _blank )

I get the same result when trying different combinations of links.

**Comment by frozzare** [comment] 2015-10-12 08:01
Fixed in `2.4.0-dev`, the problem was that `url` as slug was removed since it will remove the numeric value on format value and that I didn't check that the value was numeric or not.

**Closed by frozzare** 2015-10-12 08:01 UTC
Labels: waiting for reporter

**Comment by frozzare** [comment] 2015-10-12 08:34
Pro tip: you don't have to use `get_template_directory_uri` in `template`. Just write `template => page-templates/teaser.php`

**Comment by danfri86** [comment] 2015-10-12 08:38
Great, thank you.
Yeah, I've noticed :+1:  using it from now on!
