### ISSUE TITLE
Color field not working

### ISSUE THREAD

**Issue by richardsweeney** [wp-papi/papi#179] opened 2016-07-29 06:48 UTC
The color picker doesn't work. I tried adding it to a repeater field and to a single field but it's not working. You can't pick a different color.

![colorpicker](https://cloud.githubusercontent.com/assets/761071/17240071/3378a774-5569-11e6-9fad-f05b3abe9c5c.png)

- Browser: Chrome (51)
- Papi: 3.1.3
- WordPress: 4.5.3

**Comment by frozzare** [comment] 2016-07-29 07:00
I think there is a problem with the color picker in wp, I will take another look at this and see if I can do anything in Papi to fix it.

**Comment by nlemoine** [comment] 2016-10-21 12:15
I can confirm this issue too. I'm currently looking into it. 

Here's what I found out: 

1 - There's an issue with `palettes` property.  
Default is an array: https://github.com/wp-papi/papi/blob/master/src/properties/class-papi-property-color.php#L16
If no settings are provided, this returns an empty array to the `palettes` property of the options object passed to `wpColorPicker`. Default should be `true`. 

2 - There's another issue (palettes are buggy when clicked) caused by this: https://github.com/wp-papi/papi/blob/master/src/assets/js/properties/color.js#L44-L46
Is there any reason you want to trigger `change` on the input? I didn't look deeper but looks like no function is binded to this event. 

Actually, some options in papi doesn't exist in `wpColorPicker`: https://github.com/WordPress/WordPress/blob/master/wp-admin/js/color-picker.js#L13-L20
Is there a reason here too?

**Comment by frozzare** [comment] 2016-10-21 12:19
1. yep, will take a look at the color picker for 3.2
2. I think this was a solution for a older version of wordpress, maybe not needed anymore.
3. Not all options that exists in papi is options for the color picker, the property can have own options, so that's isn't a problem.

**Comment by frozzare** [comment] 2016-10-23 13:45
1. The `palettes` options that will give a a empty array isn't a problem since it's checked in the js code https://github.com/wp-papi/papi/blob/161664a7e3e2620953f0a61964ff5ab67a01be7a/src/assets/js/properties/color.js#L45
2. Removed the double `change` event and it's seems that it works better. Could you try it out @nlemoine or @richardsweeney? (`3.x` branch)
3. What about adding all options that exists for `wpColorPicker` to the property? (maybe not the `target` option)

**Comment by nlemoine** [comment] 2016-10-24 12:18
1. If `palettes` array is empty, palettes should return `true`, not false (I think most people expect the ability to choose colors, not only some colors from black to white): 
`!palettes.length ? true : palettes`
But even when passing `true` to palettes, an empty array is still passed to the `wpColorPicker`. If you take a look at WordPress color picker code, options passed to `wpColorPicker` are merged with the ones found in element data: https://github.com/WordPress/WordPress/blob/master/wp-admin/js/color-picker.js#L31
And Papi uses a data attributes named `data-palettes` to get the palettes array. So the empty array found in data attributes overrrides the `true` value returned by Papi. 

So there's no need to pass palettes (or any other options) through papi JS, these lines could actually be removed: https://github.com/wp-papi/papi/blob/f546c801300433cb4eb3690f02271d2a84241713/src/assets/js/properties/color.js#L36
https://github.com/wp-papi/papi/blob/f546c801300433cb4eb3690f02271d2a84241713/src/assets/js/properties/color.js#L44

The only thing you need is set the data attribute `data-palettes` on the input element accordingly: https://github.com/wp-papi/papi/blob/f546c801300433cb4eb3690f02271d2a84241713/src/properties/class-papi-property-color.php#L32
`'data-palettes' => $settings->palettes ? $settings->palettes : true,`

2. Yes, this resolves the palettes click issue. 

3. Why not. What's the target option, I can't see it? https://github.com/WordPress/WordPress/blob/master/wp-admin/js/color-picker.js#L13-L21

**Comment by frozzare** [comment] 2016-10-24 12:23
1. Wow, why is the standalone version of  `wpColorPicker` different from the build in, so bad. The documentation of [iris.js](http://automattic.github.io/Iris/) says `false` on `palettes`. 
2. Good.
3. Same as 1, the standalone version of `wpColorPicker` is different from WordPress's. But adding all options that are relevant isn't so hard, just time consuming :)

**Comment by frozzare** [comment] 2016-10-25 06:40
1. Should be right now according to `wpColorPicker` and not `iris.js` since the diff.
3. Created a new issue for adding all options to 3.2.0 instead of 3.1.16. https://github.com/wp-papi/papi/issues/202

**Comment by nlemoine** [comment] 2016-10-25 09:30
Thanks! 👍

**Closed** 2016-10-25 13:03 UTC
Labels: bug
