### ISSUE TITLE
in 3.0.8, Options Page, Checkbox property not saved

### ISSUE THREAD

**Issue by chrisvidal** [wp-papi/papi#175] opened 2016-05-25 03:46 UTC
the property options page does not save any value anymore, even the test folder provided does not save with WP 4.5.2 in my case

**Comment by chrisvidal** [comment] 2016-05-25 03:51
ok, now the save button seems to be active again, dont know what happened here.

anyway, now i see that checkbox property does not save properly.
When checked, the value is saved,
When unchecked, the value is not saved

**Comment by frozzare** [comment] 2016-05-25 05:34
Please follow the issue template that exists in this repository.

I can't reproduce this with 3.0.8 and WP 4.5.2, the save button on a option page works and the checkbox value is saved. Have you tested this on a clean WP 4.5.2 site with only Papi and no other plugins?

**Comment by frozzare** [comment] 2016-05-25 05:36
When I did another test i could reproduce this. You kind of right with your issue description, the checkbox property values isn't removed, but the save button works.

**Comment by frozzare** [comment] 2016-05-25 05:40
This should now be fixed in https://github.com/wp-papi/papi/commit/5ecd9296769541fcbde6a40efbf38a32a8b10f36, can you confirm that this fix also works for you?

**Comment by chrisvidal** [comment] 2016-05-25 07:37
perfect, i confirm it is working as expected with this fix.

thanks a lot for your speedyness

**Closed** 2016-05-25 08:44 UTC
Labels: Bug
